services:
  - type: web
    name: family-tree
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8888
      - key: NO_BROWSER
        value: "1"
      - key: DB_PATH
        value: /app/data/family_tree.db
      - key: PHOTO_DIR
        value: /app/data/photos
